version: '3.8'

services:
  model-runner:
    image: docker/dev-model-runner:beta
    platform: linux/arm64  # For Apple Silicon
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - model-runner-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "9222:9222"
    environment:
      - SE_NODE_SESSION_TIMEOUT=180
      - SE_START_XVFB=false
      - SE_START_NO_SANDBOX=true
    volumes:
      - chrome-data:/home/seluser
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: dockerfiles/almalinux/Dockerfile
    depends_on:
      chrome:
        condition: service_healthy
      model-runner:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - CHROME_URL=ws://chrome:9222
      - MODEL_RUNNER_URL=http://model-runner:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent-data:/app/data
      - ./agent/mcp.json:/app/mcp.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(process.uptime() > 30 ? 0 : 1)"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model-runner-data:
  chrome-data:
  agent-data:
