version: '3.8'

services:
  model-runner:
    image: docker/dev-model-runner:beta
    platform: linux/arm64  # For Apple Silicon
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - model-runner-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "9222:9222"
    environment:
      - SE_NODE_SESSION_TIMEOUT=180
      - SE_START_XVFB=false
      - SE_START_NO_SANDBOX=true
    volumes:
      - chrome-data:/home/seluser
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: dockerfiles/almalinux/Dockerfile
    depends_on:
      chrome:
        condition: service_healthy
      model-runner:
        condition: service_healthy
    services:
  agent:
    build:
      context: .
      dockerfile: dockerfiles/almalinux/Dockerfile
    environment:
      - WORKSPACE_DOMAIN=${WORKSPACE_DOMAIN:-localhost}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCKER_MODEL_RUNNER_BASE_URL=http://model-runner.docker.internal:12434
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_memory:/dev/shm  # Shared memory for browser automation
    depends_on:
      - chrome
      - model-runner

volumes:
  model-runner-data:
  chrome-data:
  agent-data:
